### ISSUE TITLE
Security 

### ISSUE THREAD

**Issue by FrankFeenix** [vinci6k/curving-flash#1]
Is this legal? Does it get banned only from the VAC?

**Comment by vinci6k** [comment]
Since this is a server side plugin (made using [Source.Python](https://github.com/Source-Python-Dev-Team/Source.Python/)), it's completely legal and safe to use.

**Comment by FrankFeenix** [comment]
Would be very grateful if there was a clip showing how to install Source Python, unzip the directory and create the path

**Comment by vinci6k** [comment]
Not a problem, I'll post the clip later today or tomorrow.

**Comment by FrankFeenix** [comment]
Man. Im still waiting for your instructions. Can u post it up? Thanks

**Comment by vinci6k** [comment]
Apologies, I've been somewhat busy the past few days. The video is rendering as we speak, and you can expect to see it later today, seeing as I'm heading to bed right now. 😅

**Comment by FrankFeenix** [comment]
Haha. Thought you forgot. Hopefully tomorrow I'll catch it. Thank you very much for your enthusiasm bro

**Comment by vinci6k** [comment]
Here you go mate: https://www.youtube.com/watch?v=oaL2E7p3HLg
